# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WaterLinkedSonarIntegrationProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)WaterLinkedSonarIntegrationProtocol.proto\x12\x1awaterlinked.sonar.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"+\n\x06Packet\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"L\n\x06Header\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bsequence_id\x18\x02 \x01(\r\"\xa7\x02\n\x15\x42itmapImageGreyscale8\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".waterlinked.sonar.protocol.Header\x12\x16\n\x0espeed_of_sound\x18\x02 \x01(\x02\x12\r\n\x05range\x18\x03 \x01(\x02\x12\x11\n\tfrequency\x18\x04 \x01(\r\x12\x39\n\x04type\x18\x05 \x01(\x0e\x32+.waterlinked.sonar.protocol.BitmapImageType\x12\r\n\x05width\x18\x06 \x01(\r\x12\x0e\n\x06height\x18\x07 \x01(\r\x12\x16\n\x0e\x66ov_horizontal\x18\x08 \x01(\x02\x12\x14\n\x0c\x66ov_vertical\x18\t \x01(\x02\x12\x18\n\x10image_pixel_data\x18\n \x01(\x0c\"\xfc\x01\n\nRangeImage\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".waterlinked.sonar.protocol.Header\x12\x16\n\x0espeed_of_sound\x18\x02 \x01(\x02\x12\r\n\x05range\x18\x03 \x01(\x02\x12\x11\n\tfrequency\x18\x04 \x01(\r\x12\r\n\x05width\x18\x05 \x01(\r\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\x16\n\x0e\x66ov_horizontal\x18\x07 \x01(\x02\x12\x14\n\x0c\x66ov_vertical\x18\x08 \x01(\x02\x12\x19\n\x11image_pixel_scale\x18\t \x01(\x02\x12\x18\n\x10image_pixel_data\x18\n \x03(\r*>\n\x0f\x42itmapImageType\x12\x19\n\x15SIGNAL_STRENGTH_IMAGE\x10\x00\x12\x10\n\x0cSHADED_IMAGE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WaterLinkedSonarIntegrationProtocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BITMAPIMAGETYPE']._serialized_start=809
  _globals['_BITMAPIMAGETYPE']._serialized_end=871
  _globals['_PACKET']._serialized_start=133
  _globals['_PACKET']._serialized_end=176
  _globals['_HEADER']._serialized_start=178
  _globals['_HEADER']._serialized_end=254
  _globals['_BITMAPIMAGEGREYSCALE8']._serialized_start=257
  _globals['_BITMAPIMAGEGREYSCALE8']._serialized_end=552
  _globals['_RANGEIMAGE']._serialized_start=555
  _globals['_RANGEIMAGE']._serialized_end=807
# @@protoc_insertion_point(module_scope)
